# Generated by Django 4.1.11 on 2023-11-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_projects_language_requirement_projects_last_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('icon_name', models.CharField(blank=True, max_length=100)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('icon_organization', models.CharField(blank=True, max_length=100)),
                ('language_requirement', models.CharField(blank=True, max_length=255, null=True)),
                ('icon_language', models.CharField(blank=True, max_length=100)),
                ('Gender', models.CharField(blank=True, max_length=255, null=True)),
                ('icon_gender', models.CharField(blank=True, max_length=100)),
                ('requirement_documents', models.CharField(blank=True, max_length=255, null=True)),
                ('icon_documents', models.CharField(blank=True, max_length=100)),
                ('last_date', models.DateField(blank=True, max_length=255, null=True)),
                ('icon_lastDate', models.CharField(blank=True, max_length=100)),
                ('number_opportunity', models.IntegerField(blank=True, max_length=255, null=True)),
                ('icon_id', models.CharField(blank=True, max_length=100)),
                ('link', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('eligibility_criteria', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='projects',
            name='catagory',
        ),
    ]
