# Generated by Django 4.1.11 on 2023-11-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_projects_2_remove_projects_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects_2',
            name='number_opportunity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
