# Generated by Django 4.1.11 on 2023-11-01 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_projects_2_number_opportunity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='projects_2',
            new_name='new',
        ),
    ]
