# Generated by Django 4.1.11 on 2023-11-01 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_projects_2_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='icon_documents',
        ),
        migrations.RemoveField(
            model_name='new',
            name='icon_gender',
        ),
        migrations.RemoveField(
            model_name='new',
            name='icon_id',
        ),
        migrations.RemoveField(
            model_name='new',
            name='icon_language',
        ),
        migrations.RemoveField(
            model_name='new',
            name='icon_lastDate',
        ),
        migrations.RemoveField(
            model_name='new',
            name='icon_name',
        ),
        migrations.RemoveField(
            model_name='new',
            name='icon_organization',
        ),
    ]
