# Generated by Django 4.1.11 on 2023-11-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_new_icon_documents_remove_new_icon_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='name',
            new_name='Degree',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='organization',
            new_name='Duration',
        ),
        migrations.AddField(
            model_name='new',
            name='Language_Instruction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='field_study',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='opportunity_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='province_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='scholarship_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
