# Generated by Django 4.1.11 on 2023-11-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_name_new_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
